CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, categoryText TEXT);
CREATE TABLE IF NOT EXISTS domains (domainText TEXT NOT NULL, categoryId INTEGER NOT NULL, CONSTRAINT PK_DOMAINS PRIMARY KEY (domainText, categoryId));
